### ISSUE TITLE
Move Files From Generative Art Project Template

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#1]
# Description

We need to move the source code files from the [generative art project template repo](https://github.com/brittni-and-the-polar-bear/generative-art-project-template) to this repo.

# Tasks

- [x] clone repository locally
- [x] set up all dependencies
- [x] move current library source files
- [x] move unit test source files
- [x] run unit tests locally successfully
- [x] set up protected branches
- [x] set up protected tags
  - [x] this repo
  - [x] project template repo
- [x] set up code scanning
- [x] set up dependency scanning
