### ISSUE TITLE
Implement HSL Range Color Factories

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#10]
# Description

Implement range color factories for HSL colors.

# Tasks

- [ ] implement for all previously established hue ranges
  - [ ] all
  - [ ] top
  - [ ] bottom
  - [ ] warm
  - [ ] cool
  - [ ] missing any?
- [ ] regular range (high saturation, 50% lightness)
- [ ] deep range (high saturation, low lightness)
- [ ] pastel range (low saturation, high lightness)
- [ ] single hue with full range of saturation and brightness
- [ ] range of hues with full range of saturation and brightness
