### ISSUE TITLE
2024-07-28: Fix Order of `BRITTNI` Palette

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/generative-art-library#120]
# Description

The colors in the `BRITTNI` palette should be in the following order.

<script src="https://coolors.co/palette-widget/widget.js"></script>
<script data-id="043706044226081664">new CoolorsPaletteWidget("043706044226081664", ["121212","0437f2","ff6bb5","7a00f5","0fff4f"]); </script>

# Tasks

- [x] update order in palette
- [x] update order in palette documentation
- [x] update order in palette explorer markdown
- [x] check for other update locations

**Comment by azurepolarbear** [comment]
This item is staged. Development is complete.
