### ISSUE TITLE
Implement Color Palettes

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#125]
# Description

This is a running list of color palettes that we would like to implement in the library.

## Palette Types
- holiday
  - christmas
  - halloween
  - 4th of july
  - easter
  - new year's eve
  - valentine's day
  - thanksgiving
  - kwanza
  - hanukkah
  - st. patrick's day
- artists
  - mondrian
  - van gogh
    - starry night
    - almond trees
    - sunflowers
  - da vinci
  - monet
  - renoir
- characters
  - hello kitty
  - kuromi
  - winnie the pooh
  - kiki
- people
  - edgar alan poe
  - mary shelley
  - emily dickinson
- pride flags
  - pride
  - gay
  - lesbian
  - bisexual
  - transgender
  - asexual
  - demisexual
  - pansexual
- nature
  - watermelon
  - bluebonnet
  - water lily
  - trees
  - fall leaves
- sports
  - dallas cowboys
  - atlanta braves
  - san antonio spurs
  - smu
  - florida gators
  - grambling tigers
  - tennessee state tigers
  - howard university
- miscellaneous
  - olympic rings
  - brittni's hair
- gradients
- color hunt palettes
- random coolors palettes
- mindful palettes (X)

# Tasks

palette name (category): [link to palette information, if available]()

- [ ] christmas eve (christmas): [color hex: christmas eve](https://www.color-hex.com/color-palette/96876)
- [ ] christmas snow (christmas): [color hex: christmas snow](https://www.color-hex.com/color-palette/78520)
- [ ] nightmare before christmas (haloween): [color hex: nightmare before christmas](https://www.color-hex.com/color-palette/56388)
- [ ] shine (valentines): [culrs: shine](https://culrs.com/palette/f4357bd81b60c2185bad1457880e4f)
- [ ] bring on the neon (misc): [color hex: bring on the neon](https://www.color-hex.com/color-palette/1036985)
- [ ] iced mocha (misc): [color hex: iced mocha](https://www.color-hex.com/color-palette/1032496)
- [ ] gingerbread espresso (misc): [color hex: gingerbread espresso](https://www.color-hex.com/color-palette/96593)
- [x] blue lily (nature): [color hex: blue lily](https://www.color-hex.com/color-palette/1040636)
- [ ] white lily (nature): [color hex: white lily](https://www.color-hex.com/color-palette/1039504)
- [ ] succulent (nature): [color hex: succulent](https://www.color-hex.com/color-palette/7459)
- [ ] lilac flowers (nature): [color hex: lilac flowers](https://www.color-hex.com/color-palette/1030535)
- [ ] goth babe (halloween): [color hex: goth babe](https://www.color-hex.com/color-palette/1041199)
- [ ] kilgrave clothes (halloween): [color hex: kilgrave clothes](https://www.color-hex.com/color-palette/1039335)
- [ ] deathkiss (halloween): [color hex: deathkiss](https://www.color-hex.com/color-palette/1038791)
- [ ] midnight serentity (nature): [color hex: midnight serenity](https://www.color-hex.com/color-palette/1037158)
- [ ] demisexual flag (pride): [flagcolorcodes: demisexual flag](https://www.flagcolorcodes.com/demisexual)
- [ ] bisexual flag (pride): [flagcolorcodes: bisexual flag](https://www.flagcolorcodes.com/bisexual)
- [ ] transgender flag (pride): [flagcolorcodes: transgender flag](https://www.flagcolorcodes.com/transgender)
- [ ] dallas cowboys (sports): [flagcolorcodes: dallas cowboys](https://www.flagcolorcodes.com/dallas-cowboys)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/fdc5f5-f7aef8-b388eb-8093f1-72ddf7-ffffff-d0d0d0-121212)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/121212-393d3f-d3d4d6-928e80-857c7b-334956-223843-19414d-28253a)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/121212-181818-282828-535353-1db954-1dc95b-ffffff)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/ffffff-efefef-e5e5e5-1d3557-cccccc-4c4c4c-121212)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/ff6bb5-3a214a-341d40-231429)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/470024-6b0036-94004a-c20061-f5007a-ff2e96-ff6bb5-ff94c9-ffb8db)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/0070c0-0088c4-00a1c7-00b9cb-00d1ce-40b8c8-809ec2-bf85bb-ff6bb5)
- [ ] unnamed (mermaid?): [coolors palette](https://coolors.co/palette/0070c0-0088c4-00a1c7-00b9cb-00d1ce-40b8c8-809ec2-bf85bb-ff6bb5)
- [ ] unnamed (blue moon?): [coolors palette](https://coolors.co/palette/0437f2-63b0cd-5adbff-ffc145-f7e8a4)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/33a1ff-0437f2-eef7ff-2a0c4e-f5f8de)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/0437f2-117744-63b0cd-5adbff-ffc145)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/ff4433-0437f2-fafa33-28282b-7f00ff)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/031d44-7a00f5-04395e-75bba7-331650)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/290052-390073-5200a3-6600cc-7a00f5)
- [ ] unnamed (saved by the bell?): [coolors palette](https://coolors.co/palette/f65f13-f910a4-2c9cf2-7a00f5-91ff0a)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/fffaff-0f1108-f5b8c6-7a00f5-dc2e96)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/31c1ed-007af5-2d058a-7a00f5)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/330066-7a00f5-6600cc-d7cbf6-171717)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/8ee000-d500e0-7a00f5-00a7f5)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/00e0bf-d500e0-7a00f5-00a7f5)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/240750344c64577b8d57a6a1)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/1534483c5b6f948979dfd0b8)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/003c43135d6677b0aae3fef7)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/86469cbc7fcdfb9ad1ffcdea)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/f8f6e397e7e16ad4dd7aa2e3)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/22283131363f76abaeeeeeee)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/2650732d95969ad0c2f1fada)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/070f2b1b1a55535c919290c3)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/6c22a66962ad83c0c196e9c6)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/0306373c0753720455910a67)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/f2afefc499f37360df33186b)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/3924675d3587a367b1ffd1e3)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/52d3d83887be38419d200e3a)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/c5fff896efff5fbdff7b66ff)
- [ ] unnamed: [color hunt palette](https://colorhunt.co/palette/f1eaffe5d4ffdcbfffd0a2f7)
- [ ] s+b teal: [color-hex: s+b teal palette](https://www.color-hex.com/color-palette/309)
- [ ] Miss Mayhem too: [color-hex: Miss Mayhem too palette](https://www.color-hex.com/color-palette/1031623)
- [ ] 002: [color-hex: 002 palette](https://www.color-hex.com/color-palette/2854)
- [ ] Lunar Twilight: [color-hex: Lunar Twilight palette](https://www.color-hex.com/color-palette/65295)
- [ ] California wine sunset: [color-hex: California wine sunset palette](https://www.color-hex.com/color-palette/107525)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/b8e4ff-fafeff-282d3b)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/fdfbed-fafeff-9ecefa-63b5f8-0d89e7)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/60a9b6-ccd0d5-75919c-fafeff-196a71)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/0070c0-0088c4-00a1c7-00b9cb-00d1ce-40b8c8-809ec2-bf85bb-ff6bb5)
- [ ] unnamed: [coolors palette](https://coolors.co/palette/ff6bb5-22223b-fbfbf2-e5e6e4-9ec5ff)
