### ISSUE TITLE
Feature Request - Weighted Palettes

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/generative-art-library#126]
# Description

Implement palettes where each color has some weight that determines the color selection distribution.

# Tasks

- [ ] implement weighted palette class
- [ ] implement weighted palette unit tests
- [ ] implement weighted palette color selector
- [ ] implement weighted palette color selector unit tests
- [ ] implement adapter that creates a randomly weighted palette from a regular palette.
- [ ] create weighted palettes
  - [ ] palette 1
    - [ ] palette
    - [ ] unit tests
  - [ ] palette 2
    - [ ] palette
    - [ ] unit tests
  - [ ] palette 3
    - [ ] palette
    - [ ] unit tests
