### ISSUE TITLE
2024-07-29 - Refactor and Move RGB Repository

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/generative-art-library#127]
# Description

Refactor and move the generative art library RGB repository.

# Tasks

- [ ] Refactor and move the generative art library [rgb repository](https://github.com/brittni-and-the-polar-bear/generative-art-library_color_rgb)
  - [ ] move source files
  - [ ] move unit test files
  - [ ] run eslint
  - [ ] run unit tests
  - [ ] generate documentation
  - [ ] publish new package version
  - [ ] test new version
    - [ ] check "tree-shaking". make sure unnecessary classes/variables are being excluded.
  - [ ] move repo issues
  - [ ] mark repository as archive
