### ISSUE TITLE
Implement Dependency Security Scanning

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#13]
# Description

Implement security scanning for project dependencies.

# Tasks

- [x] research if dependency security workflow is different from dependency update workflow
- [x] add dependency security scanning to actions
- [x] add passing scan as a pull request requirement
- [x] add badge to README
- [x] test action running in a pull request
