### ISSUE TITLE
2024-07-30 - Make Jekyll Collection for Palettes

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#131]
# Description

Turn the sets of `Palette` documentation files into Jekyll collections.

Documentation for collections can be found on the [Jekyll website](https://jekyllrb.com/docs/collections/).

# Tasks

- [ ] create the jekyll palettes collection
- [ ] create an example palette with front matter, content, and tags
- [ ] create an example palette collection page
- [ ] test with multiple palettes
- [ ] test with multiple palette categories
- [ ] can you output palettes by tag/collection where palettes show up on multiple pages sorted by category
- [ ] create all palette files
- [ ] update links in palette collection documentation
