### ISSUE TITLE
2024-07-30 - Make Jekyll Collection for Release Notes

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#132]
# Description

Turn the sets of release notes documentation files into Jekyll collections.

Documentation for collections can be found on the [Jekyll website](https://jekyllrb.com/docs/collections/).

# Tasks

- [ ] create the release notes jekyll collection
- [ ] create an example release note with front matter, content, and tags
- [ ] make release notes pages for major versions
- [ ] make release notes pages for minor versions
- [ ] make release notes page for all versions (include release dates)
- [ ] test release notes in different folders
- [ ] update links in release tag information
