### ISSUE TITLE
2024-08-01 - Review rules in stylistic eslint plugin

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#137]
# Description

Review all the rules in the [`@stylistic/eslint-plugin`](https://eslint.style/) plugin and decide which ones should be configured in the eslint configuration file.

# Tasks

- [ ] review all rules
- [ ] implement chosen rules
- [ ] run eslint and ensure that it passes
