### ISSUE TITLE
2024-08-04 - Review rules in eslint plugin

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#139]
# Description

Review all the rules in the [`eslint-plugin`](https://eslint.org/) plugin and decide which ones should be configured in the eslint configuration file.

# Tasks

- [ ] review all rules
- [ ] implement chosen rules
- [ ] run eslint and ensure that it passes
