### ISSUE TITLE
Implement Initial Color Scheme Generation

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#14]
# Description

Create the initial classes for the color scheme creation in generative art projects.

# Tasks

- [x] Color class
- [x] ~~Color builder~~
- [x] ~~ColorGroup class~~
- [x] ~~Implement color transitions in both directions~~
  - [x] ~~Transparency Transition~~ (Addressed in #58)
  - [x] ~~Lerp Transition~~ (Addressed in #58)

**Comment by azurepolarbear** [comment]
Closing this issue because it is now OBE. The changes addressed in this issue can be handled in additional, more granular issues.
