### ISSUE TITLE
Bug Report - 2024-08-10 - ColorSelectors should return a copy of the Color

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#142]
### Browser Name

Chrome

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/brittni-and-the-polar-bear/.github/tree/main?tab=coc-ov-file#readme).

### Issue Description

The PaletteColorSelector and ColorSelector classes should return a copy of the colors, not the color objects contained in the selectors.

# Tasks
- [x] `Color` copy method
- [x] `Color` constructor that accepts a `Color` object
- [x] `PaletteColorSelector` color returning methods
- [x] `ColorSelector` color returning methods

**Comment by blwatkins** [comment]
This item is staged. Development is complete.
