### ISSUE TITLE
Feature Request - Random Palette Builder

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/generative-art-library#151]
# Description

I would like a Palette builder that can select random `PaletteColor` objects to build a palette.

# Tasks

- [ ] select a given number of colors from a list
- [ ] select a random number of color from a list
- [ ] select a given number of colors from all palette colors
- [ ] select a random number of colors from all palette colors
- [ ] select colors from weighted lists
  - weight determines which list to pull from
  - colors in list are chosen with even distribution, then removed from the list
  - [ ] select a random number of colors
  - [ ] select a given number of colors
