### ISSUE TITLE
Feature Request - Keyboard Mapper

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#161]
# Description

A static class that maps whatever key has been pressed to a function that needs to be called when that key is pressed.

# Tasks

- [ ] map character to void function
- [ ] map keycode to void function
- [ ] capture key strokes to execute mapped functions
- [ ] lock mappings so they cannot be replaced
- [ ] method to set multiple mappings at once
- [ ] KeyMapping object/type/interface structure - (key/keycode, function, isLocked)
- [ ] Retrieve mappings for mobile UI
