### ISSUE TITLE
Update Color Unit Tests to Test Color Creation with HEX strings

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#4]
# Description

Unit tests for the Color class need to be updated to test that they behave properly when built from a color created with a hexadecimal color string.

# Tasks
- [ ] color from hex string constructor
- [ ] color from hex string setter method
- [ ] color from invalid hex string constructor
- [ ] color from invalid hex string setter method
