### ISSUE TITLE
Move Full Library Into Main Repository

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/generative-art-library#53]
# Description

With the new configuration, we can use paths without any issues! Fantastic!

Now, we need to consolidate the base, color palette, and rgb repositories into this repository.

# Tasks

- [x] [base repository](https://github.com/brittni-and-the-polar-bear/generative-art-library_base)
  - [x] move source files
  - [x] move unit test files
  - [x] update README
  - [x] run eslint
  - [x] run unit tests
  - [x] run size-limit
  - [x] generate documentation
  - [x] publish new version of repo
  - [x] test new version in [color test repo](https://github.com/azurepolarbear/batpb-genart_test_color)
    - [x] check "tree-shaking". make sure unnecessary classes/variables are being excluded.
  - [x] deprecate latest versions of [@batbp/genart-base](https://www.npmjs.com/package/@batpb/genart-base)
  - [x] deprecate whole package
  - [x] move repo issues
  - [x] mark repository as archive
- [x] [color palettes repository](https://github.com/brittni-and-the-polar-bear/generative-art-library_color_palettes)
  - [x] move source files
  - [x] move unit test files
  - [x] run eslint
  - [x] run unit tests
  - [x] r~~un size-limit~~
  - [x] generate documentation
  - [x] publish new version of repo
  - [x] test new version in [color test repo](https://github.com/azurepolarbear/batpb-genart_test_color)
    - [x] check "tree-shaking". make sure unnecessary classes/variables are being excluded.
  - [x] deprecate latest versions of [@batbp/genart-palettes](https://www.npmjs.com/package/@batpb/genart-palettes)
  - [x] deprecate whole package
  - [x] move repo issues
  - [x] mark repository as archive

Remaining tasks covered in #127 
- [x] ~~[rgb repository](https://github.com/brittni-and-the-polar-bear/generative-art-library_color_rgb)~~
  - [x] ~~move source files~~
  - [x] ~~move unit test files~~
  - [x] ~~run eslint~~
  - [x] ~~run unit tests~~
  - [x] ~~run size-limit~~
  - [x] ~~generate documentation~~
  - [x] ~~publish new version of repo~~
  - [x] ~~test new version in [color test repo](https://github.com/azurepolarbear/batpb-genart_test_color)~~
    - [x] ~~check "tree-shaking". make sure unnecessary classes/variables are being excluded.~~
  - [x] ~~move repo issues~~

**Comment by blwatkins** [comment]
Issue will be closed later today, but it is not quite ready to be closed yet.
