### ISSUE TITLE
Feature Request - 2024-04-25 - Lerp Color Functions

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#58]
# Description

Implement functionality to steadily transition between colors.

There should be an option to lerp all color components at once (using the lerpColor method) or lerp one color component at a time.

# Tasks

- [ ] lerp all components
- [ ] lerp one component at a time
  - [ ] provided component order
  - [ ] random component order
- [ ] unit tests
