### ISSUE TITLE
Configure Passing Unit Tests as a Pull Request Requirement

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#6]
# Description

We want an actions workflow that runs the unit tests and reports a pass or fail. These tests must pass successfully as a requirement of a valid pull request.

# Tasks

- [x] create unit test workflow
- [x] test action success
- [x] test action failure
- [x] make action a requirement of pull requests
- [x] test action failure in a pull request
- [x] test action success in a pull request

**Comment by azurepolarbear** [comment]
GitHub Action successfully configured.
