### ISSUE TITLE
Create Canvas Context Class

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#61]
# Description

When we set `WEBGL` for the p5 canvas renderer, the origin of the canvas moves to the center. The values returned by `mouseX` and `mouseY` are not updated to reflect this change, so the values end up being larger than what is valid on the canvas.

We need a class that will handle any translations that need to happen when using the `WEBGL` renderer in a 2D context, as we usually do.

# Tasks

- [ ] Create Basic Context Class
- [ ] Ability to Set Renderer Mode
- [ ] Get mouseX and mouseY properly depending on mode
- [ ] Get center of canvas coordinates
  - [ ] (0, 0) when using `WEBGL` renderer
  - [ ] (width / 2.0, height / 2.0) with default renderer
- [ ] Map from (0, width) to (-width / 2.0, width / 2.0) when using `WEBGL` renderer
- [ ] Map from (0, height) to (-height / 2.0, height / 2.0) when using `WEBGL` renderer
