### ISSUE TITLE
Feature Request - Add Color Name Retrieval to Library

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/generative-art-library#66]
# Description

Implement a way to get the closest color name using the [color name list](https://www.npmjs.com/package/color-name-list?activeTab=readme) and [nearest color](https://github.com/dtao/nearest-color) packages.

See [color name list documentation](https://www.npmjs.com/package/color-name-list?activeTab=readme#closest-named-color) for example.

# Tasks

- [x] integrate getting color names into library
- [x] test getting color names for colors
- [x] get colors for ~palettes and~ generative color

**Comment by blwatkins** [comment]
# Considerations

* check color name list for name first
* if not present, find nearest color
* cache results by hex

**Comment by blwatkins** [comment]
# Update

- [ ] Remove color-name-list dependency

Color names will come from colors already programmed into the library (PaletteColors)
