### ISSUE TITLE
Feature Request - 2024-05-13 - Add eslint-plugin-security to Project

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#74]
# Description

Add [eslint-plugin-security](https://www.npmjs.com/package/eslint-plugin-security), [eslint-plugin-n](https://github.com/eslint-community/eslint-plugin-n), and [eslint-plugin-es-x](https://github.com/eslint-community/eslint-plugin-es-x) packages to project. Test and make sure they are compatible with TypeScript.

If the addition is successful, add them to the template project.

# Tasks

- [x] update eslint plugins
- [x] add eslint-plugin-security
- [x] add eslint-plugin-n
- [x] add eslint-plugin-es-x
