### ISSUE TITLE
Feature Request - 2024-05-16 - MappableColorSelector Interface

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/generative-art-library#76]
# Description

We want a way to indicate for certain color selectors that you can map a range of values to a color in the selector.  This can be applicable to palettes (e.g. gradient palettes) or HSL selectors (e.g. mapping to a hue value).

# Tasks

- [ ] Create MappableColorSelector Interface
- [ ] PaletteColorSelector should implement the interface
- [ ] add a flag in PaletteColorSelector (isMapLerpActive)
  - when flag is true, map will lerp between colors in the indexes
  - when flag is false, map will choose integer index for color
