### ISSUE TITLE
Create GitHub Pages for Library

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#8]
# Description

We need a GitHub Pages site to serve as the homepage of the library.

# Tasks

- [x] add `docs/` directory
- [x] add initial `index.md` file
- [x] begin pages deployment
- [x] add `docs/` directory to ignored files for TypeScript compilation and Rollup bundling
  - [x] test locally to make sure `docs/` files are not included in package export
