### ISSUE TITLE
Feature Request - 2024-06-01 - String Validator

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/generative-art-library#92]
# Description

We want to add a `StringValidator` class.  The only methods right now will be confirming that something is a valid RGB hex string (#RRGGBB) or a valid RGBA hex string (#RRGGBBAA).

The logic for these checks already exist in the unit tests (`/src/test/shared/color.ts`: `checkForValidHexColorString(hex: string)`.

# Tasks

- [ ] create class
- [ ] implement valid RGB hex string check
- [ ] test valid RGB hex string check
- [ ] implement valid RGBA hex string check
- [ ] test valid RGBA hex string check

**Comment by azurepolarbear** [comment]
Duplicates #91
